var adatok =
[
    {
      "rank": 1,
      "team": "Chelsea",
      "played": 38,
      "wins": 26,
      "draws": 9,
      "losses": 3,
      "goalsfor": 73,
      "goalsagainst": 32,
      "goalsdiff": "+41",
      "points": 87
    },
    {
      "rank": 2,
      "team": "Manchester City",
      "played": 38,
      "wins": 24,
      "draws": 7,
      "losses": 7,
      "goalsfor": 83,
      "goalsagainst": 38,
      "goalsdiff": "+45",
      "points": 79
    },
    {
      "rank": 3,
      "team": "Arsenal",
      "played": 38,
      "wins": 22,
      "draws": 9,
      "losses": 7,
      "goalsfor": 71,
      "goalsagainst": 36,
      "goalsdiff": "+35",
      "points": 75
    },
    {
      "rank": 4,
      "team": "Manchester United",
      "played": 38,
      "wins": 20,
      "draws": 10,
      "losses": 8,
      "goalsfor": 62,
      "goalsagainst": 37,
      "goalsdiff": "+25",
      "points": 70
    },
    {
      "rank": 5,
      "team": "Tottenham Hotspur",
      "played": 38,
      "wins": 19,
      "draws": 7,
      "losses": 12,
      "goalsfor": 58,
      "goalsagainst": 53,
      "goalsdiff": "+5",
      "points": 64
    },
    {
      "rank": 6,
      "team": "Liverpool",
      "played": 38,
      "wins": 18,
      "draws": 8,
      "losses": 12,
      "goalsfor": 52,
      "goalsagainst": 48,
      "goalsdiff": "+4",
      "points": 62
    },
    {
      "rank": 7,
      "team": "Southampton",
      "played": 38,
      "wins": 18,
      "draws": 6,
      "losses": 14,
      "goalsfor": 54,
      "goalsagainst": 33,
      "goalsdiff": "+21",
      "points": 60
    },
    {
      "rank": 8,
      "team": "Swansea City",
      "played": 38,
      "wins": 16,
      "draws": 8,
      "losses": 14,
      "goalsfor": 46,
      "goalsagainst": 49,
      "goalsdiff": -3,
      "points": 56
    },
    {
      "rank": 9,
      "team": "Stoke City",
      "played": 38,
      "wins": 15,
      "draws": 9,
      "losses": 14,
      "goalsfor": 48,
      "goalsagainst": 45,
      "goalsdiff": "+3",
      "points": 54
    },
    {
      "rank": 10,
      "team": "Crystal Palace",
      "played": 38,
      "wins": 13,
      "draws": 9,
      "losses": 16,
      "goalsfor": 47,
      "goalsagainst": 51,
      "goalsdiff": -4,
      "points": 48
    },
    {
      "rank": 11,
      "team": "Everton",
      "played": 38,
      "wins": 12,
      "draws": 11,
      "losses": 15,
      "goalsfor": 48,
      "goalsagainst": 50,
      "goalsdiff": -2,
      "points": 47
    },
    {
      "rank": 12,
      "team": "West Ham United",
      "played": 38,
      "wins": 12,
      "draws": 11,
      "losses": 15,
      "goalsfor": 44,
      "goalsagainst": 47,
      "goalsdiff": -3,
      "points": 47
    },
    {
      "rank": 13,
      "team": "West Bromwich Albion",
      "played": 38,
      "wins": 11,
      "draws": 11,
      "losses": 16,
      "goalsfor": 38,
      "goalsagainst": 51,
      "goalsdiff": -13,
      "points": 44
    },
    {
      "rank": 14,
      "team": "Leicester City",
      "played": 38,
      "wins": 11,
      "draws": 8,
      "losses": 19,
      "goalsfor": 46,
      "goalsagainst": 55,
      "goalsdiff": -9,
      "points": 41
    },
    {
      "rank": 15,
      "team": "Newcastle United",
      "played": 38,
      "wins": 10,
      "draws": 9,
      "losses": 19,
      "goalsfor": 40,
      "goalsagainst": 63,
      "goalsdiff": -23,
      "points": 39
    },
    {
      "rank": 16,
      "team": "Sunderland",
      "played": 38,
      "wins": 7,
      "draws": 17,
      "losses": 14,
      "goalsfor": 31,
      "goalsagainst": 53,
      "goalsdiff": -22,
      "points": 38
    },
    {
      "rank": 17,
      "team": "Aston Villa",
      "played": 38,
      "wins": 10,
      "draws": 8,
      "losses": 20,
      "goalsfor": 31,
      "goalsagainst": 57,
      "goalsdiff": -26,
      "points": 38
    },
    {
      "rank": 18,
      "team": "Hull City",
      "played": 38,
      "wins": 8,
      "draws": 11,
      "losses": 19,
      "goalsfor": 33,
      "goalsagainst": 51,
      "goalsdiff": -18,
      "points": 35
    },
    {
      "rank": 19,
      "team": "Burnley",
      "played": 38,
      "wins": 7,
      "draws": 12,
      "losses": 19,
      "goalsfor": 28,
      "goalsagainst": 53,
      "goalsdiff": -25,
      "points": 33
    },
    {
      "rank": 20,
      "team": "Queens Park Rangers",
      "played": 38,
      "wins": 8,
      "draws": 6,
      "losses": 24,
      "goalsfor": 42,
      "goalsagainst": 73,
      "goalsdiff": -31,
      "points": 30
    }
  ]